%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Ross\Documents\Work\Postdoc\St_Andrews\Output\Private_Papers\Jurikova_et_al_202X\Data\Data_Compilation_SrCOB.xlsx
%    Worksheet: FullComp1
%
% Auto-generated by MATLAB on 25-Oct-2021 14:14:37

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 19);

% Specify sheet and range
opts.Sheet = "FullComp1";
opts.DataRange = "A2:S1004";

% Specify column names and types
opts.VariableNames = ["Original_Sequence", "Sr87", "Sr87_SD", "Sample", "Stage", "Formation", "Age", "CI", "AgeDetermination", "Species", "Author", "d13C", "d18O", "Sr87_OriginalReported", "Notes", "d11B", "d11B_Reproducibility_2SD", "d11B_Error_2SD", "d11B_Method"];
opts.VariableTypes = ["double", "double", "double", "string", "categorical", "categorical", "double", "double", "categorical", "categorical", "categorical", "double", "double", "double", "string", "double", "double", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Sample", "Notes", "d11B_Method"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Sample", "Stage", "Formation", "AgeDetermination", "Species", "Author", "Notes", "d11B_Method"], "EmptyFieldRule", "auto");

% Import the data
DataCompilationSrCOB = readtable("C:\Users\Ross\Documents\Work\Postdoc\St_Andrews\Output\Private_Papers\Jurikova_et_al_202X\Data\Data_Compilation_SrCOB.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts